project:
  type: website

website:
  title: "PsychGen Wiki"
  navbar:
    background: primary
    left:
      - text: "About"
        href: about.qmd
      - text: "TSD"
        href: tsd.qmd
      - text: "New analytic project"
        href: new_analytic.qmd
      - text: "Phenotypic data"
        href: pheno.qmd
      - text: "Colossus"
        href: colossus.qmd
    right:
      - text: "Other resources"
        menu:
        - R_resources.qmd
    tools:
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/amslala/psychgen-test
            target: _blank
            
  sidebar:
    - title: "TSD"
      style: "docked"
      background: light
      contents: 
        - tsd.qmd
        - tsd_1.qmd
        - tsd_2.qmd
        - tsd_3.qmd
    - title: "Phenotypic data"
      contents: 
        - pheno.qmd
        - pheno_1.qmd
        - pheno_2.qmd
        - pheno_3.qmd
        
  page-footer:
    background: light 
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

execute:
  freeze: auto