project:
  type: website

website:
  title: "PsychGen documentation"
  navbar:
    background: primary
    left:
      - text: "About"
        href: about.qmd
      - text: "TSD"
        href: tsd.qmd
      - other.qmd
    right:
      - text: "Other resources"
        menu:
        - R_resources.qmd
    tools:
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/amslala/my-website
            
  sidebar:
    - title: "TSD"
      style: "docked"
      background: light
      contents: 
        - tsd.qmd
        - tsd_1.qmd
        - tutorials-2.qmd
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto