project:
  type: website

website:
  title: "PsychGen documentation"
  navbar:
    background: primary
    left:
      - text: "About"
        href: about.qmd
      - text: "TSD"
        href: tsd.qmd
      - text: "New analytic project"
        href: new_analytic.qmd
      - text: "Phenotypic data"
        href: pheno.qmd
    right:
      - text: "Other resources"
        menu:
        - R_resources.qmd
    tools:
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/amslala/psychgen-test
            
  sidebar:
    - title: "TSD"
      style: "docked"
      background: light
      contents: 
        - tsd.qmd
        - tsd_1.qmd
        - tsd_2.qmd
        - tsd_3.qmd
    - title: "Phenotypic data"
      contents: 
        - pheno.qmd
        - pheno_1.qmd
      
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto